### ISSUE TITLE
Abnormal measurement values

### ISSUE THREAD

**Issue by StevenCellist** [dok-net/esp_sds011#11]
Hi Dirk and thanks for your surprisingly functional library.
I hooked up one of my SDS011 sensors and am reading quite absurd values. Both pm2.5 and pm10 read about 200~300 every time. Assuming that the measurements are in ug/m³, this is a tad bit high ;)
Does this indeed sound weird, or is my assumption wrong?
Moreover - could you provide a sketch that runs in continuous mode with just single measurements? The async is throwing me a bit off and for troubleshooting I'd love a simple sketch which measures continuously. I could probably hack it myself but if you have something..

Cheers! Steven

**Comment by StevenCellist** [comment]
By the way - any chance v1.1 can be released straight to the Arduino IDE? 😄 currently it's running on v1.0.1

**Comment by dok-net** [comment]
I don't know why the Arduino library management "bot" never seems to have picked up release 1.1.0. We shall see what happens to 2.0.0 when time comes.
Please devise a sketch for your debugging needs on your own, it's statedly not a good idea to start the sensor and keep it running, as the documentation clearly mentions a seriously shortened time of life in that case.
Your readings are high, yes, but how certain can you be that they are both incorrect and due to anything this library has something to do with? Indoor activities like cooking, showering, air moisturizers are sufficient sources of particulate matter for that level. You should perform a check in a well ventilated area with clean, moderately warm air, with no condensation.

**Comment by StevenCellist** [comment]
Thanks for your reply! I compared the measurements to the SDS011 connected to an Arduino and using some library for the Arduino. In that case, the measurements were still elevated but not nearly as high as using the ESP and your library. I have seen such behaviour before when the voltage is slightly different which may or may not be the case with my ESP32, but I remembered I have an SPS30 as well which I will use instead because of lower power consumption. I will close this issue.
