### ISSUE TITLE
Rampup time

### ISSUE THREAD

**Issue by netmaniac** [dok-net/esp_sds011#4]
Default rampup time is 10 second (10 packets). According to Laser Dust Sensor Control Protocol from Novafitness, after wakeup 30 seconds is needed to wait before taking measurements (https://nettigo.pl/attachments/415 note to sleep command on page 4). Shouldn't it be changed?

**Comment by dok-net** [comment]
I disagree. IIRC the 10s rampup in this library have been verified to provide stable readings. As far as www.inovafitness.com goes, it's a bit contradictory, so I tend toward the empirical finding plus the most sensible interpretation of what transpires there. In excerpts from the specification 1.3 and the protocol documentation 1.3:
> 2. Quick response: response time is less than 10 seconds when the 
scene changes;

> On the occasion of 
real-time demand is not high (such as filter, air quality monitoring, etc.), 
you can use the discontinuous working method to prolong the service 
life. For example, you can start the sensor for 30 seconds per minutes.

>Notes: The data is stable when the sensor works after 30 seconds;
The fan and laser stop working in sleeping mode.

> work 30 seconds and sleep n*60-30 seconds

Now, it can only be one, either work 30 seconds, then stop, and have some useful readings, not just a single one at the end, or rampup for 30s and ...

Do you have compelling evidence that between 10s and 30s there is a relevant change in the readings?

**Comment by netmaniac** [comment]
No, we won't have any data (yet), just note in document from Novafitness.

We plan to do some tests comparing different settings, however we don't have any deadline for that test...

**Comment by dok-net** [comment]
@netmaniac But can you agree that Novafitness isn't completely unambiguous?

**Comment by dok-net** [comment]
By the way, during the past 2 years environmental particulate matter  pollution has been very low. My original tests for data stability and rampup duration were performed on relevant PM presence. There are two way for a household setting to get elevated readings. Either cook a meal. Or use an ultrasound air humidifier filled with regular hard tap water. You can let the micro-droplets evaporate all you want, the SDS011 proves that there is a measurable health risk involved in using tap water containing so many minerals that are not exactly suitable for inhalation at a 2.5µm size, because the PM concentration becomes extremely high in closed spaces. By comparison to use with desalinated water, I think there is causation, not just correlation, at work.

**Comment by dok-net** [comment]
There is `Sds011::set_data_rampup()`. That makes this a non-issue. I'm closing.
